version: '2'
services:
    costshare-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/costshare/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=costshare
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
